/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.JavaY2.InventoryManager;

import com.mycompany.JavaY2.Object.Receive;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Kaiqi
 */
public class im_update_stock extends javax.swing.JFrame {

    /**
     * Creates new form im_update_stock
     */
    public im_update_stock() {
        initComponents();
        jComboBox1.removeAllItems();
        String file_path = "src/main/java/com/mycompany/JavaY2/TextFile/receives";

        try (BufferedReader br = new BufferedReader(new FileReader(file_path))) {
            String line;
            br.readLine();

            while ((line = br.readLine()) != null) {
                String[] data = line.split("\\|");
                String orderId = data[0];
                if(data[6].equals("Not Received")){
                jComboBox1.addItem(orderId);              
                }
            }
        } catch (IOException e) {
            System.out.println("Error reading file: " + e.getMessage());
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1500, 750));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jButton1.setText("Update Stocks");

        jButton2.setText("List of Items");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Generate Stock Report");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{
                "Order ID", "Item ID", "Item Name", "Quantity", "Amount", "Date Received", "Status", "Payment Date", "Payment Status"
            }){
                @Override
                public boolean isCellEditable(int row, int column){
                    return false;
                }
            };
            jTable1.setModel(model);
            com.mycompany.JavaY2.InventoryManager.TextFileHandling tfh = new com.mycompany.JavaY2.InventoryManager.TextFileHandling();
            List<Receive> receiveList = tfh.getReceiveList();

            for (Receive receive : receiveList){
                Object[] rowData = {
                    receive.getOrderId(),
                    receive.getItemId(),
                    receive.getItemName(),
                    receive.getQuantity(),
                    receive.getAmount(),
                    receive.getDateReceived(),
                    receive.getStatus(),
                    receive.getPaymentDate(),
                    receive.getPaymentStatus()
                };
                model.addRow(rowData);
            }
            jScrollPane1.setViewportView(jTable1);

            jButton6.setText("Update Stock");
            jButton6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton6ActionPerformed(evt);
                }
            });

            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{ "Item 1", "Item 2", "Item 3", "Item 4" }));
            jComboBox1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBox1ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 34, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(67, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(40, 40, 40))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String usernameEntered = JOptionPane.showInputDialog(this, "Enter username: ");
        String passwordEntered = JOptionPane.showInputDialog(this, "Enter password: ");
        boolean authorized = false;
        
        String users_file_path = "src/main/java/com/mycompany/JavaY2/TextFile/users";
        
        try(BufferedReader br = new BufferedReader(new FileReader(users_file_path))){
            String line;
            br.readLine();
            
            while((line = br.readLine()) != null){
                String[] data = line.split("\\|");
                String username = data[1];
                String password = data[2];
                String role = data[3];
                
                if(usernameEntered.equals(username) && passwordEntered.equals(password)){
                    if (role.equalsIgnoreCase("inventory manager")){
                        authorized = true;
                        break;
                    }else {
                        JOptionPane.showMessageDialog(this, "Access denied. Only inventory managers can perform this action.");
                        return;
                }
            }
        }
            if(!authorized){
                JOptionPane.showMessageDialog(this, "Invalid username or password.");
                return;
            }
        }catch (IOException e){
            System.out.println(e.getMessage());
        }
        
        
        String selectedOrderId = (String) jComboBox1.getSelectedItem();
        if (selectedOrderId == null) return;
        
        String receives_file_path = "src/main/java/com/mycompany/JavaY2/TextFile/receives";
        String inventory_file_path = "src/main/java/com/mycompany/JavaY2/TextFile/inventory";
        
        List<String> updateReceiveStatus = new ArrayList<>();
        String itemNameUpdate = null;
        String currentDate = java.time.LocalDate.now().format(java.time.format.DateTimeFormatter.ofPattern("ddMMyyyy"));
        int receiveQuantityUpdate = 0;
        boolean alreadyUpdated = false;
        
        try (BufferedReader br = new BufferedReader(new FileReader(receives_file_path))){
            String line;
            while ((line = br.readLine()) != null){
                String[] data = line.split("\\|");
                
                if (data[0].equals(selectedOrderId)){
                    if(data[6].equals("Received")){
                        alreadyUpdated = true;
                    } else{
                    itemNameUpdate = data[2].trim();
                    receiveQuantityUpdate = Integer.parseInt(data[3].trim());
                    data[5] = currentDate;
                    data[6] = "Received";
                    line = String.join("|", data);
                    }
                }
                updateReceiveStatus.add(line);
            }
        }catch (IOException e){
            System.out.println("Error reading receives.txt: " + e.getMessage());
            return;
        }
        
        if (alreadyUpdated) {
            JOptionPane.showMessageDialog(this, "This Order ID has already been updated.");
            return;
        }
        
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(receives_file_path))){
            for (String updatedLine : updateReceiveStatus){
                bw.write(updatedLine);
                bw.newLine();
            }
        }catch (IOException e){
            System.out.println(e.getMessage());
        }
        
        List<String> updateQuantityinInventory = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader(inventory_file_path))){
            String line;
            while((line = br.readLine()) != null){
                String[] data = line.split("\\|");
                
                if(data[1].trim().equals(itemNameUpdate)){
                    int currentQuantity = Integer.parseInt(data[2].trim());
                    int updatedQuantity = currentQuantity + receiveQuantityUpdate;
                    data[2] = String.valueOf(updatedQuantity);
                    line = String.join("|", data);
                }
                updateQuantityinInventory.add(line);
            }
        }catch (IOException e){
            System.out.println(e.getMessage());
        }
        
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(inventory_file_path))){
            for(String updatedLine : updateQuantityinInventory){
                bw.write(updatedLine);
                bw.newLine();
            }
        }catch (IOException e){
            System.out.println(e.getMessage());
        }
        
        JOptionPane.showMessageDialog(this, "Stock updated successfully!");
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(im_update_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(im_update_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(im_update_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(im_update_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new im_update_stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
