/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.JavaY2.InventoryManager;

import com.mycompany.JavaY2.Class.DataMapping;
import com.mycompany.JavaY2.Class.TextFile;
import com.mycompany.JavaY2.Object.Item;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kaiqi
 */
public class im_view_items extends javax.swing.JFrame {
    private final String item_file_path = "src/main/java/com/mycompany/JavaY2/TextFile/items";
    private final String supplier_file_path = "src/main/java/com/mycompany/JavaY2/TextFile/suppliers";

    private final DefaultTableModel itemContainer = new DefaultTableModel();
    private final String itemTableColumnName[] = {"Item ID", "Item Name", "Stock Price", "Sales per day", 
                                                  "Ordering Lead Time (Days)", "Safety Level", "Supplier", "Group ID"};

    /** Creates new form im_view_items */
    public im_view_items() {
        initComponents();
        populateItemTable();
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowActivated(java.awt.event.WindowEvent evt) {
                itemContainer.setRowCount(0);
                populateItemTable();     
            }
        });
        
        item_search_bar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemSearchFunction(item_search_bar.getText());
            }
        });
    }
    
    private void populateItemTable(){
        DataMapping mapping = new DataMapping();
        Map<String, String> supplier_map = mapping.IdNameMapping(supplier_file_path);
        Map<Integer, Map<String, String>> column_mappings = new HashMap<>();
        column_mappings.put(6, supplier_map); // supplier_id column
        TextFile.populateTable(itemContainer, item_table, itemTableColumnName, item_file_path, 50,column_mappings);         
    }
    
    private void itemSearchFunction(String item_keyword) {
        itemContainer.setRowCount(0); // Clear existing rows
        item_keyword = item_keyword.toLowerCase().trim();
        
        if (item_keyword.isEmpty()) {
            populateItemTable(); // <- call your full data loader
            return;
        }
            
        DataMapping mapping = new DataMapping();
        Map<String,String> supplier_map = mapping.IdNameMapping(supplier_file_path);

        try (BufferedReader br = new BufferedReader(new FileReader(item_file_path))) {
            String item_line;
            Set<String> uniqueItemRows = new HashSet<>();
            br.readLine(); // skip header

            while ((item_line = br.readLine()) != null) {
                if (!item_line.trim().isEmpty() && !uniqueItemRows.contains(item_line)) {
                    String[] item_details = item_line.split("\\|");

                    // Create an Item object from the line
                    Item item = new Item(
                        item_details[0], // item_id
                        item_details[1], // item_name
                        Double.parseDouble(item_details[2]), // stock_price
                        Integer.parseInt(item_details[3]), // sales_per_day
                        Integer.parseInt(item_details[4]), // ordering_lead_time
                        Integer.parseInt(item_details[5]), // safety_level
                        item_details[6], // supplier_id
                        item_details[7]  // group_id
                    );

                    if (item.anyMatch(item_keyword)) {
                        // Replace supplier_id with supplier_name
                        item_details[6] = supplier_map.get(item_details[6]);
                        itemContainer.addRow(item_details);
                        uniqueItemRows.add(item_line);
                    }
                }
            }

        } catch (IOException e) {
            System.out.println("Error reading item file during search: " + e.getMessage());
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        item_table = new javax.swing.JTable();
        item_search_bar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 750));
        setSize(new java.awt.Dimension(1500, 750));

        item_table.setModel(itemContainer);
        jScrollPane1.setViewportView(item_table);

        item_search_bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_search_barActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Search: ");

        jButton5.setText("< Back to Mainpage");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(item_search_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(189, 189, 189)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(402, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_search_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item_search_barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_search_barActionPerformed
        String item_keyword = item_search_bar.getText();
        itemSearchFunction(item_keyword);
    }//GEN-LAST:event_item_search_barActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new im_mainpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(im_view_items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(im_view_items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(im_view_items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(im_view_items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new im_view_items().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField item_search_bar;
    private javax.swing.JTable item_table;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
