/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javaY2.SalesManagerGUI;
import com.mycompany.JavaY2.Class.TextFile;
import com.mycompany.JavaY2.Object.Item;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
/**
 *
 * @author User
 */
public class Sales_manager_add_item extends javax.swing.JFrame {

    /**
     * Creates new form sales_manager_add_item
     */
    public Sales_manager_add_item() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_item_label = new javax.swing.JLabel();
        item_name_label = new javax.swing.JLabel();
        item_name_label1 = new javax.swing.JLabel();
        item_name_label2 = new javax.swing.JLabel();
        item_name_label3 = new javax.swing.JLabel();
        item_name_label4 = new javax.swing.JLabel();
        item_name_textfield = new javax.swing.JTextField();
        supplier_name_textfield = new javax.swing.JTextField();
        stock_price_spinner = new javax.swing.JSpinner();
        sales_per_day_spinner = new javax.swing.JSpinner();
        ordering_lead_time_spinner = new javax.swing.JSpinner();
        add_item_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        add_item_label.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label.setText("Key in the details of new item.");

        item_name_label.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_label.setText("Supplier Name:");

        item_name_label1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_label1.setText("Item Name:");

        item_name_label2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_label2.setText("Stock Price:");

        item_name_label3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_label3.setText("Sales Per Day:");

        item_name_label4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_label4.setText("Ordering Lead Time:");

        item_name_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        supplier_name_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        stock_price_spinner.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        stock_price_spinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 1000.0d, 0.1d));
        stock_price_spinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        sales_per_day_spinner.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        sales_per_day_spinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        ordering_lead_time_spinner.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        ordering_lead_time_spinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        add_item_button.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_button.setText("Add Item");
        add_item_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_item_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item_name_label2)
                    .addComponent(item_name_label1)
                    .addComponent(item_name_label3)
                    .addComponent(item_name_label4)
                    .addComponent(item_name_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(supplier_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(item_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(116, 116, 116))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(stock_price_spinner)
                                .addComponent(sales_per_day_spinner)
                                .addComponent(ordering_lead_time_spinner))
                            .addContainerGap()))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(428, 428, 428)
                        .addComponent(add_item_button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(add_item_label)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(add_item_label)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(item_name_label1))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stock_price_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(item_name_label2))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sales_per_day_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(item_name_label3))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ordering_lead_time_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(item_name_label4))
                        .addGap(47, 47, 47)
                        .addComponent(item_name_label))
                    .addComponent(supplier_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(add_item_button)
                .addGap(59, 59, 59))
        );

        stock_price_spinner.setEditor(new javax.swing.JSpinner.NumberEditor(stock_price_spinner, "0.00"));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_item_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_item_buttonActionPerformed
        String item_file_path = "src\\main\\java\\com\\mycompany\\JavaY2\\TextFile\\items";
        String inventory_file_path = "src\\main\\java\\com\\mycompany\\JavaY2\\TextFile\\inventory";
        
        Item item = new Item();
        
        String item_id = item.setItemID();
        String item_name = item_name_textfield.getText().toLowerCase();
        double stock_price = (double) stock_price_spinner.getValue();
        stock_price = Double.parseDouble(String.format("%.2f", stock_price));
        int sales_per_day = (int) sales_per_day_spinner.getValue();
        int ordering_lead_time = (int) ordering_lead_time_spinner.getValue();
        String supplier_name = supplier_name_textfield.getText();
        String group_id = item.setGroupID(item_name);
        
        String item_details = item_id + "|" + item_name + "|" + stock_price + "|" + sales_per_day + "|" + ordering_lead_time + "|" + supplier_name + "|" + group_id;        
        
        if (item_name.isEmpty() || supplier_name.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please fill in all the fields");
            
        }else if(Item.checkIsNewGroupID(group_id)){
            int quantity = 0;
            double retail_price =0;
            
            JSpinner jSpinner_quantity = new JSpinner(new SpinnerNumberModel(0, 0, 1000, 1));
            JSpinner jSpinner_retail_price = new JSpinner(new SpinnerNumberModel(0.0, 0.0, 10000.0, 0.1));

            JPanel panel = new JPanel();
            panel.add(new JLabel("Quantity: "));
            panel.add(jSpinner_quantity);
            panel.add(new JLabel("Retail Price: "));
            panel.add(jSpinner_retail_price);

                // Show JOptionPane with the Panel
            int result = JOptionPane.showConfirmDialog(null, panel, "Enter Item Details", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

            if (result != JOptionPane.OK_OPTION) {
                JOptionPane.showMessageDialog(this, "User cancelled input.");
                return;
            }
            
            quantity = (int) jSpinner_quantity.getValue();
            retail_price = (double) jSpinner_retail_price.getValue();
            retail_price = Double.parseDouble(String.format("%.2f", retail_price));
            if (quantity < 0 || retail_price < 0) {
                JOptionPane.showMessageDialog(this, "Quantity and Retail Price must be greater than zero.");
            }
            
            String inventory_details = group_id + "|" + item_name + "|" + quantity + "|" + retail_price;
            TextFile.addLine(inventory_file_path, inventory_details);
            TextFile.addLine(item_file_path, item_details);
            JOptionPane.showMessageDialog(this,"New item with new group has been added successfully, inventory is updated");
            this.dispose();
            
        }else{
            TextFile.addLine(item_file_path, item_details);
            JOptionPane.showMessageDialog(this,"New item been added successfully");
            this.dispose();            
        }
        

        
        
        
    }//GEN-LAST:event_add_item_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales_manager_add_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales_manager_add_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales_manager_add_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales_manager_add_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales_manager_add_item().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_item_button;
    private javax.swing.JLabel add_item_label;
    private javax.swing.JLabel item_name_label;
    private javax.swing.JLabel item_name_label1;
    private javax.swing.JLabel item_name_label2;
    private javax.swing.JLabel item_name_label3;
    private javax.swing.JLabel item_name_label4;
    private javax.swing.JTextField item_name_textfield;
    private javax.swing.JSpinner ordering_lead_time_spinner;
    private javax.swing.JSpinner sales_per_day_spinner;
    private javax.swing.JSpinner stock_price_spinner;
    private javax.swing.JTextField supplier_name_textfield;
    // End of variables declaration//GEN-END:variables
}
