/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.JavaY2.SalesManagerGUI;

import com.mycompany.JavaY2.Class.TextFile;
import com.mycompany.JavaY2.Object.DailySale;
import com.mycompany.javaY2.Class.DataMapping;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class SM_daily_sales_add extends javax.swing.JFrame {
    private final String inventory_file_path = "src\\main\\java\\com\\mycompany\\JavaY2\\TextFile\\inventory";
    private final String daily_sales_file_path = "src\\main\\java\\com\\mycompany\\JavaY2\\TextFile\\daily_sales_items";
    /**
     * Creates new form SM_daily_sales_add
     */
    public SM_daily_sales_add() {
        initComponents();
        populateItemComboBox();
        setCurrentDate();
        setRetailPrice();
        calculateTotalAmount();
        
        quantity_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                calculateTotalAmount();
            }
        });
        
        item_combo_box.addActionListener(new java.awt.event.ActionListener() {
            @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                setRetailPrice();
                calculateTotalAmount();
            }
        });
    }
    
    private void populateItemComboBox(){
        try{
            BufferedReader br = new BufferedReader(new FileReader(inventory_file_path));
            String line;
            br.readLine(); // Skip header line

            while ((line = br.readLine()) != null) {
                String[] columns = line.split("\\|");
                if (columns.length >= 2) {
                    String item_name = columns[1].trim();
                    item_combo_box.addItem(item_name);
                }
            }
        }catch(IOException e){
            System.out.println("Error reading inventory textfile");
        }
        
    }
    
    private void setCurrentDate(){
        Date current_date = new Date();
        SimpleDateFormat date_format = new SimpleDateFormat("ddMMyyyy");
        String formatted_date = date_format.format(current_date);
        date_textfield.setText(formatted_date);
    }
    
    private void setRetailPrice(){
        DataMapping mapping = new DataMapping();
        Map<String,String> item_retail_price_map = mapping.NameRetailPriceMapping(inventory_file_path);
        String selected_item = (String) item_combo_box.getSelectedItem();
        String retail_price = item_retail_price_map.get(selected_item);
        retail_price_textfield.setText(retail_price);
    } 
    
    private void calculateTotalAmount(){
        int quantity = (int) quantity_spinner.getValue();
        double retail_price = Double.parseDouble(retail_price_textfield.getText());
        double total_amount = quantity*retail_price;
        total_amount_textfield.setText(String.format("%.2f", total_amount));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_item_label1 = new javax.swing.JLabel();
        add_item_label = new javax.swing.JLabel();
        add_item_label2 = new javax.swing.JLabel();
        add_item_label3 = new javax.swing.JLabel();
        add_item_label4 = new javax.swing.JLabel();
        add_item_label5 = new javax.swing.JLabel();
        item_combo_box = new javax.swing.JComboBox<>();
        retail_price_textfield = new javax.swing.JTextField();
        total_amount_textfield = new javax.swing.JTextField();
        date_textfield = new javax.swing.JTextField();
        cancel_add_sales_button = new javax.swing.JButton();
        add_sales_button = new javax.swing.JButton();
        quantity_spinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 750));
        setPreferredSize(new java.awt.Dimension(1000, 750));

        add_item_label1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label1.setText("Enter the details of the sales:");

        add_item_label.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label.setText("Selected Item:");

        add_item_label2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label2.setText("Quantity:");

        add_item_label3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label3.setText("Retail Price:");

        add_item_label4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label4.setText("Total Amount:");

        add_item_label5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label5.setText("Date:");

        item_combo_box.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        retail_price_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        retail_price_textfield.setEnabled(false);
        retail_price_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retail_price_textfieldActionPerformed(evt);
            }
        });

        total_amount_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        total_amount_textfield.setEnabled(false);
        total_amount_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_amount_textfieldActionPerformed(evt);
            }
        });

        date_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        date_textfield.setEnabled(false);
        date_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_textfieldActionPerformed(evt);
            }
        });

        cancel_add_sales_button.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cancel_add_sales_button.setText("Cancel");
        cancel_add_sales_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_add_sales_buttonActionPerformed(evt);
            }
        });

        add_sales_button.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_sales_button.setText("Add Sales");
        add_sales_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_sales_buttonActionPerformed(evt);
            }
        });

        quantity_spinner.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        quantity_spinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addComponent(cancel_add_sales_button, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(add_sales_button)
                .addGap(261, 261, 261))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(add_item_label5)
                            .addComponent(add_item_label4)
                            .addComponent(add_item_label3)
                            .addComponent(add_item_label2)
                            .addComponent(add_item_label))
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(item_combo_box, 0, 388, Short.MAX_VALUE)
                            .addComponent(retail_price_textfield)
                            .addComponent(total_amount_textfield)
                            .addComponent(date_textfield, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(quantity_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(add_item_label1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(add_item_label1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add_item_label)
                    .addComponent(item_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_item_label2)
                    .addComponent(quantity_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retail_price_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_item_label3))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_amount_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_item_label4))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_item_label5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_sales_button)
                    .addComponent(cancel_add_sales_button))
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retail_price_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retail_price_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retail_price_textfieldActionPerformed

    private void total_amount_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_amount_textfieldActionPerformed
 
    }//GEN-LAST:event_total_amount_textfieldActionPerformed

    private void date_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_textfieldActionPerformed

    private void cancel_add_sales_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_add_sales_buttonActionPerformed
        JOptionPane.showMessageDialog(this,"You have cancel adding new sales record. Back to daily sales mainpage now.");
        this.dispose();
    }//GEN-LAST:event_cancel_add_sales_buttonActionPerformed

    private void add_sales_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_sales_buttonActionPerformed
        DailySale sales = new DailySale();
        
        String daily_sales_id = sales.setSalesID();
        String selected_item = (String) item_combo_box.getSelectedItem();
        int quantity = (int) quantity_spinner.getValue();
        double retail_price = Double.parseDouble(retail_price_textfield.getText());
        String date = date_textfield.getText();
        
        DataMapping mapping = new DataMapping();
        Map<String, String> item_map = mapping.NameIdMapping(inventory_file_path);
        String group_id = item_map.get(selected_item);
        
        String sales_details = daily_sales_id + "|" + quantity + "|" + group_id + "|" + retail_price + "|" + date;
        

        if (quantity <=0){
            JOptionPane.showMessageDialog(this, "Please enter a valid item quantity.");
        }else{
            boolean update_inventory = DailySale.updateInventoryQuantity(this, group_id, quantity);
            if (update_inventory){
                TextFile.addLine(daily_sales_file_path, sales_details);
                JOptionPane.showMessageDialog(this, "New sales record has been added.");
                this.dispose();                   
            }
        }
    }//GEN-LAST:event_add_sales_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SM_daily_sales_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SM_daily_sales_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SM_daily_sales_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SM_daily_sales_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SM_daily_sales_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_item_label;
    private javax.swing.JLabel add_item_label1;
    private javax.swing.JLabel add_item_label2;
    private javax.swing.JLabel add_item_label3;
    private javax.swing.JLabel add_item_label4;
    private javax.swing.JLabel add_item_label5;
    private javax.swing.JButton add_sales_button;
    private javax.swing.JButton cancel_add_sales_button;
    private javax.swing.JTextField date_textfield;
    private javax.swing.JComboBox<String> item_combo_box;
    private javax.swing.JSpinner quantity_spinner;
    private javax.swing.JTextField retail_price_textfield;
    private javax.swing.JTextField total_amount_textfield;
    // End of variables declaration//GEN-END:variables
}
