/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.JavaY2.SalesManagerGUI;

import com.mycompany.JavaY2.Class.TextFile;
import com.mycompany.JavaY2.Object.DailySale;
import com.mycompany.JavaY2.Class.DataMapping;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class SM_daily_sales_edit extends javax.swing.JFrame {
    private final String inventory_file_path = "src\\main\\java\\com\\mycompany\\JavaY2\\TextFile\\inventory";
    private final String daily_sales_file_path = "src\\main\\java\\com\\mycompany\\JavaY2\\TextFile\\daily_sales_items";
    /**
     * Creates new form SM_daily_sales_edit
     * @param sales_id
     * @param quantity
     * @param group_id
     * @param retail_price
     * @param date
     */
    public SM_daily_sales_edit(String sales_id, String quantity, String group_id, String retail_price, String date) {
        initComponents();
        sales_id_textfield.setText(sales_id);
        item_textfield.setText(group_id);
        sold_quantity_textfield.setText(quantity);
        retail_price_textfield.setText(retail_price);
        date_textfield.setText(date);
        calculateTotalAmount();
        
        quantity_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                calculateTotalAmount();
            }
        });
    }
    
    private void calculateTotalAmount(){
        int quantity = (int) quantity_spinner.getValue();
        double retail_price = Double.parseDouble(retail_price_textfield.getText());
        double total_amount = quantity*retail_price;
        total_amount_textfield.setText(String.format("%.2f", total_amount));
    }
    
    private String getSalesDetails(String sales_id) {
        String selected_item = item_textfield.getText();
        int new_quantity = (int) quantity_spinner.getValue();
        double retail_price = Double.parseDouble(retail_price_textfield.getText());
        String date = date_textfield.getText();

        DataMapping mapping = new DataMapping();
        Map<String, String> inventory_map = mapping.NameIdMapping(inventory_file_path);
        String group_id = inventory_map.get(selected_item);


        int original_sold_quantity = Integer.parseInt(sold_quantity_textfield.getText());
        int quantity_difference = original_sold_quantity - new_quantity;  
        DailySale.adjustInventoryQuantity(this, inventory_file_path, group_id, quantity_difference); 
        
        String updated_sales_details = sales_id + "|" + new_quantity + "|" + group_id + "|" + retail_price + "|" + date;
        return updated_sales_details;
        
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_item_label = new javax.swing.JLabel();
        add_item_label1 = new javax.swing.JLabel();
        add_item_label2 = new javax.swing.JLabel();
        quantity_spinner = new javax.swing.JSpinner();
        add_item_label3 = new javax.swing.JLabel();
        retail_price_textfield = new javax.swing.JTextField();
        add_item_label4 = new javax.swing.JLabel();
        total_amount_textfield = new javax.swing.JTextField();
        add_item_label5 = new javax.swing.JLabel();
        date_textfield = new javax.swing.JTextField();
        item_textfield = new javax.swing.JTextField();
        cancel_edit_sales_button = new javax.swing.JButton();
        edit_sales_button = new javax.swing.JButton();
        add_item_label6 = new javax.swing.JLabel();
        sales_id_textfield = new javax.swing.JTextField();
        sold_quantity_textfield = new javax.swing.JTextField();
        add_item_label7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 750));

        add_item_label.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label.setText("Edit the sales record.");

        add_item_label1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label1.setText("Selected Item:");

        add_item_label2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label2.setText("Sold Quantity:");

        quantity_spinner.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        quantity_spinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        add_item_label3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label3.setText("Retail Price:");

        retail_price_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        retail_price_textfield.setEnabled(false);
        retail_price_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retail_price_textfieldActionPerformed(evt);
            }
        });

        add_item_label4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label4.setText("Total Amount:");

        total_amount_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        total_amount_textfield.setEnabled(false);
        total_amount_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_amount_textfieldActionPerformed(evt);
            }
        });

        add_item_label5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label5.setText("Date:");

        date_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        date_textfield.setEnabled(false);
        date_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_textfieldActionPerformed(evt);
            }
        });

        item_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_textfield.setEnabled(false);

        cancel_edit_sales_button.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cancel_edit_sales_button.setText("Cancel");
        cancel_edit_sales_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_edit_sales_buttonActionPerformed(evt);
            }
        });

        edit_sales_button.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        edit_sales_button.setText("Edit Sales");
        edit_sales_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_sales_buttonActionPerformed(evt);
            }
        });

        add_item_label6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label6.setText("Sales ID:");

        sales_id_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        sales_id_textfield.setEnabled(false);

        sold_quantity_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        sold_quantity_textfield.setEnabled(false);

        add_item_label7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label7.setText("New Quantity:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(add_item_label5)
                                .addGap(263, 263, 263)
                                .addComponent(date_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(add_item_label4)
                                    .addComponent(add_item_label3)
                                    .addComponent(add_item_label7))
                                .addGap(120, 120, 120)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(total_amount_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(retail_price_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quantity_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(add_item_label)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(add_item_label6)
                                    .addComponent(add_item_label2))
                                .addGap(122, 122, 122)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sales_id_textfield)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sold_quantity_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                        .addGap(169, 169, 169))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(add_item_label1)
                                .addGap(120, 120, 120)
                                .addComponent(item_textfield))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(cancel_edit_sales_button, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(edit_sales_button)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(add_item_label)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sales_id_textfield)
                    .addComponent(add_item_label6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(item_textfield)
                    .addComponent(add_item_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sold_quantity_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_item_label2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_item_label7)
                    .addComponent(quantity_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_item_label3)
                    .addComponent(retail_price_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_item_label4)
                    .addComponent(total_amount_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_item_label5))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_sales_button)
                    .addComponent(cancel_edit_sales_button))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retail_price_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retail_price_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retail_price_textfieldActionPerformed

    private void total_amount_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_amount_textfieldActionPerformed

    }//GEN-LAST:event_total_amount_textfieldActionPerformed

    private void date_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_textfieldActionPerformed

    private void cancel_edit_sales_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_edit_sales_buttonActionPerformed
        JOptionPane.showMessageDialog(this,"You have cancel editing the item details. Back to item mainpage now.");
        this.dispose();
    }//GEN-LAST:event_cancel_edit_sales_buttonActionPerformed

    private void edit_sales_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_sales_buttonActionPerformed

        String sales_id = sales_id_textfield.getText();
        String updated_sales_details = getSalesDetails(sales_id);
        boolean edit_sales_success = TextFile.editTextfileRow(this, daily_sales_file_path, sales_id, 0, updated_sales_details);

        if(edit_sales_success){
            JOptionPane.showMessageDialog(this,"Sales record has been edited successfully, quantity of item in inventory is updated as well. Back to daily sales mainpage now");
            this.dispose();
        }

    }//GEN-LAST:event_edit_sales_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SM_daily_sales_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SM_daily_sales_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SM_daily_sales_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SM_daily_sales_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_item_label;
    private javax.swing.JLabel add_item_label1;
    private javax.swing.JLabel add_item_label2;
    private javax.swing.JLabel add_item_label3;
    private javax.swing.JLabel add_item_label4;
    private javax.swing.JLabel add_item_label5;
    private javax.swing.JLabel add_item_label6;
    private javax.swing.JLabel add_item_label7;
    private javax.swing.JButton cancel_edit_sales_button;
    private javax.swing.JTextField date_textfield;
    private javax.swing.JButton edit_sales_button;
    private javax.swing.JTextField item_textfield;
    private javax.swing.JSpinner quantity_spinner;
    private javax.swing.JTextField retail_price_textfield;
    private javax.swing.JTextField sales_id_textfield;
    private javax.swing.JTextField sold_quantity_textfield;
    private javax.swing.JTextField total_amount_textfield;
    // End of variables declaration//GEN-END:variables
}
