/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.JavaY2.SalesManagerGUI;

import com.mycompany.JavaY2.Class.TextFile;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class SM_item_edit extends javax.swing.JFrame {
    private final String item_file_path = "src\\main\\java\\com\\mycompany\\JavaY2\\TextFile\\items";
    private final String inventory_file_path = "src\\main\\java\\com\\mycompany\\JavaY2\\TextFile\\inventory";
    /**
     * Creates new form SM_item_edit
     * @param item_id
     * @param item_name
     * @param stock_price
     * @param sales_per_day
     * @param ordering_lead_time
     * @param safety_level
     * @param supplier_id
     * @param group_id
     */
    public SM_item_edit(String item_id, String item_name, String stock_price, String sales_per_day, String ordering_lead_time, String safety_level, String supplier_id, String group_id) {
        initComponents();  
        item_id_textfield.setText(item_id);
        item_name_textfield.setText(item_name);
        safety_level_textfield.setText(safety_level);
        supplier_name_textfield.setText(supplier_id);
        group_id_textfield.setText(group_id);
        
        sales_per_day_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                updateSafetyLevel();
            }
        });

        ordering_lead_time_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                updateSafetyLevel();
            }
        });

    }

    private void updateSafetyLevel(){
        int sales_per_day = (int) sales_per_day_spinner.getValue();
        int ordering_lead_time = (int) ordering_lead_time_spinner.getValue();
        
        int safety_level = sales_per_day * ordering_lead_time;
        safety_level_textfield.setText(String.valueOf(safety_level));
        
    }

    private String getItemDetails(String item_id) {
        String item_name = item_name_textfield.getText();
        double stock_price = (double) stock_price_spinner.getValue();
        stock_price = Double.parseDouble(String.format("%.2f", stock_price));
        int sales_per_day = (int) sales_per_day_spinner.getValue();
        int ordering_lead_time = (int) ordering_lead_time_spinner.getValue();
        int safety_level = Integer.parseInt(safety_level_textfield.getText());
        String supplier_name = supplier_name_textfield.getText();
        String group_id = group_id_textfield.getText();

        String updated_item_details = item_id + "|" + item_name + "|" + stock_price + "|" + sales_per_day + "|" + ordering_lead_time + "|" + safety_level + "|" + supplier_name + "|" + group_id;
        return updated_item_details;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_item_label = new javax.swing.JLabel();
        item_name_label1 = new javax.swing.JLabel();
        item_id_textfield = new javax.swing.JTextField();
        item_name_label2 = new javax.swing.JLabel();
        stock_price_spinner = new javax.swing.JSpinner();
        item_name_label3 = new javax.swing.JLabel();
        sales_per_day_spinner = new javax.swing.JSpinner();
        item_name_label4 = new javax.swing.JLabel();
        ordering_lead_time_spinner = new javax.swing.JSpinner();
        item_name_label = new javax.swing.JLabel();
        supplier_name_textfield = new javax.swing.JTextField();
        cancel_edit_item_button = new javax.swing.JButton();
        edit_item_button = new javax.swing.JButton();
        item_name_label5 = new javax.swing.JLabel();
        safety_level_textfield = new javax.swing.JTextField();
        item_name_label6 = new javax.swing.JLabel();
        group_id_textfield = new javax.swing.JTextField();
        item_name_label7 = new javax.swing.JLabel();
        item_name_textfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(null);

        add_item_label.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label.setText("Edit the item details.");

        item_name_label1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_label1.setText("Item ID:");

        item_id_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_id_textfield.setEnabled(false);
        item_id_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_id_textfieldActionPerformed(evt);
            }
        });

        item_name_label2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_label2.setText("Stock Price:");

        stock_price_spinner.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        stock_price_spinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 1000.0d, 0.1d));
        stock_price_spinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        item_name_label3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_label3.setText("Sales Per Day:");

        sales_per_day_spinner.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        sales_per_day_spinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        item_name_label4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_label4.setText("Ordering Lead Time:");

        ordering_lead_time_spinner.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        ordering_lead_time_spinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        item_name_label.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_label.setText("Supplier Name:");

        supplier_name_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        supplier_name_textfield.setEnabled(false);

        cancel_edit_item_button.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cancel_edit_item_button.setText("Cancel");
        cancel_edit_item_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_edit_item_buttonActionPerformed(evt);
            }
        });

        edit_item_button.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        edit_item_button.setText("Edit Item");
        edit_item_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_item_buttonActionPerformed(evt);
            }
        });

        item_name_label5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_label5.setText("Safety Level:");

        safety_level_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        safety_level_textfield.setEnabled(false);

        item_name_label6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_label6.setText("Item Group ID:");

        group_id_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        group_id_textfield.setEnabled(false);

        item_name_label7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_label7.setText("Item Name:");

        item_name_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_textfield.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(item_name_label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(item_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(item_name_label6)
                                .addGap(139, 139, 139))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(item_name_label7)
                                .addGap(191, 191, 191))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(item_name_label2)
                                .addGap(195, 195, 195)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stock_price_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(item_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(group_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(item_name_label4)
                                .addGap(47, 47, 47)
                                .addComponent(ordering_lead_time_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(item_name_label3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sales_per_day_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(192, 192, 192))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(item_name_label)
                                .addGap(129, 129, 129)
                                .addComponent(supplier_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(item_name_label5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(safety_level_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(add_item_label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(cancel_edit_item_button, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(edit_item_button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(add_item_label)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item_name_label1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item_name_label7)
                    .addComponent(item_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stock_price_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item_name_label2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sales_per_day_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item_name_label3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(item_name_label4)
                    .addComponent(ordering_lead_time_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_name_label5)
                    .addComponent(safety_level_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(item_name_label)
                    .addComponent(supplier_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(item_name_label6)
                    .addComponent(group_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_item_button)
                    .addComponent(cancel_edit_item_button))
                .addGap(18, 18, 18))
        );

        stock_price_spinner.setEditor(new javax.swing.JSpinner.NumberEditor(stock_price_spinner, "0.00"));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_edit_item_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_edit_item_buttonActionPerformed
        JOptionPane.showMessageDialog(this,"You have cancel editing the item details. Back to item mainpage now.");
        this.dispose();
    }//GEN-LAST:event_cancel_edit_item_buttonActionPerformed

    private void edit_item_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_item_buttonActionPerformed


        String item_id = item_id_textfield.getText();
        String updated_item_details = getItemDetails(item_id);
        boolean edit_item_success = TextFile.editTextfileRow(this, item_file_path, item_id, 0, updated_item_details);

        if(edit_item_success){
            JOptionPane.showMessageDialog(this,"Item has been edited successfully, back to item mainpage now");
            this.dispose();
        }
        

    }//GEN-LAST:event_edit_item_buttonActionPerformed

    private void item_id_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_id_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_id_textfieldActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SM_item_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SM_item_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SM_item_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SM_item_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_item_label;
    private javax.swing.JButton cancel_edit_item_button;
    private javax.swing.JButton edit_item_button;
    private javax.swing.JTextField group_id_textfield;
    private javax.swing.JTextField item_id_textfield;
    private javax.swing.JLabel item_name_label;
    private javax.swing.JLabel item_name_label1;
    private javax.swing.JLabel item_name_label2;
    private javax.swing.JLabel item_name_label3;
    private javax.swing.JLabel item_name_label4;
    private javax.swing.JLabel item_name_label5;
    private javax.swing.JLabel item_name_label6;
    private javax.swing.JLabel item_name_label7;
    private javax.swing.JTextField item_name_textfield;
    private javax.swing.JSpinner ordering_lead_time_spinner;
    private javax.swing.JTextField safety_level_textfield;
    private javax.swing.JSpinner sales_per_day_spinner;
    private javax.swing.JSpinner stock_price_spinner;
    private javax.swing.JTextField supplier_name_textfield;
    // End of variables declaration//GEN-END:variables
}
