/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.JavaY2.SalesManagerGUI;

import com.mycompany.JavaY2.AdminGUI.admin_profile;
import com.mycompany.JavaY2.Object.SessionManager;
import com.mycompany.JavaY2.login;

/**
 *
 * @author User
 */
public class SM_mainpage extends javax.swing.JFrame {

    /**
     * Creates new form SalesManagerHomepage
     */
    public SM_mainpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profile_button = new javax.swing.JButton();
        purchase_requisition_button = new javax.swing.JButton();
        daily_sales_button = new javax.swing.JButton();
        item_management_button = new javax.swing.JButton();
        supplier_management_button = new javax.swing.JButton();
        log_out_button = new javax.swing.JButton();
        purchase_order_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        profile_button.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        profile_button.setText("Profile");
        profile_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_buttonActionPerformed(evt);
            }
        });

        purchase_requisition_button.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        purchase_requisition_button.setText("Purchase Requisition");
        purchase_requisition_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchase_requisition_buttonActionPerformed(evt);
            }
        });

        daily_sales_button.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        daily_sales_button.setText("Daily Sales");
        daily_sales_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daily_sales_buttonActionPerformed(evt);
            }
        });

        item_management_button.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        item_management_button.setText("Item Management");
        item_management_button.setMaximumSize(new java.awt.Dimension(120, 300));
        item_management_button.setMinimumSize(new java.awt.Dimension(120, 300));
        item_management_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_management_buttonActionPerformed(evt);
            }
        });

        supplier_management_button.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        supplier_management_button.setText("Supplier Management");
        supplier_management_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_management_buttonActionPerformed(evt);
            }
        });

        log_out_button.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        log_out_button.setText("Log Out");
        log_out_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_out_buttonActionPerformed(evt);
            }
        });

        purchase_order_button.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        purchase_order_button.setText("Purchase Order");
        purchase_order_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchase_order_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(log_out_button, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(item_management_button, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 164, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(purchase_requisition_button, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(supplier_management_button, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(164, 164, 164)
                                .addComponent(daily_sales_button, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(purchase_order_button, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(164, 164, 164)
                                .addComponent(profile_button, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(104, 104, 104))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_management_button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplier_management_button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daily_sales_button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profile_button, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchase_requisition_button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchase_order_button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121)
                .addComponent(log_out_button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profile_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_buttonActionPerformed
        new admin_profile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profile_buttonActionPerformed

    private void purchase_requisition_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchase_requisition_buttonActionPerformed
        new SM_pr_mainpage().setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_purchase_requisition_buttonActionPerformed

    private void daily_sales_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daily_sales_buttonActionPerformed
        new SM_daily_sales_mainpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_daily_sales_buttonActionPerformed

    private void item_management_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_management_buttonActionPerformed
        new SM_item_mainpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_item_management_buttonActionPerformed

    private void supplier_management_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_management_buttonActionPerformed
        new SM_supplier_mainpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_supplier_management_buttonActionPerformed

    private void log_out_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_out_buttonActionPerformed
        new login().setVisible(true);
        SessionManager.clearCache();
        this.dispose();
    }//GEN-LAST:event_log_out_buttonActionPerformed

    private void purchase_order_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchase_order_buttonActionPerformed
        new SM_po_mainpage().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_purchase_order_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SM_mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SM_mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SM_mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SM_mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SM_mainpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton daily_sales_button;
    private javax.swing.JButton item_management_button;
    private javax.swing.JButton log_out_button;
    private javax.swing.JButton profile_button;
    private javax.swing.JButton purchase_order_button;
    private javax.swing.JButton purchase_requisition_button;
    private javax.swing.JButton supplier_management_button;
    // End of variables declaration//GEN-END:variables
}
