/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.JavaY2.SalesManagerGUI;

import com.mycompany.JavaY2.Class.TextFile;
import javax.swing.JOptionPane;
import com.mycompany.JavaY2.Object.PurchaseRequisition;
import com.mycompany.JavaY2.Class.DataMapping;
import com.mycompany.JavaY2.Class.ValidateFormat;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import com.mycompany.JavaY2.Object.SessionManager;
import java.util.Map;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
/**
 *
 * @author User
 */
public class SM_pr_add extends javax.swing.JFrame {
    private final String pr_file_path = "src/main/java/com/mycompany/JavaY2/TextFile/purchase_requisitions";
    private final String inventory_file_path = "src/main/java/com/mycompany/JavaY2/TextFile/inventory";
    /**
     * Creates new form SM_pr_add
     */
    public SM_pr_add() {
        initComponents();
        populateItemComboBox();
    }
    
    private void populateItemComboBox(){
        try{
            BufferedReader br = new BufferedReader(new FileReader(inventory_file_path));
            String line;
            br.readLine(); // Skip header line

            while ((line = br.readLine()) != null) {
                String[] columns = line.split("\\|");
                if (columns.length >= 2) {
                    String item_name = columns[1].trim();
                    item_combo_box.addItem(item_name);
                }
            }
        }catch(IOException e){
            System.out.println("Error reading inventory textfile");
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_sales_button = new javax.swing.JButton();
        cancel_add_sales_button = new javax.swing.JButton();
        quantity_spinner = new javax.swing.JSpinner();
        add_item_label1 = new javax.swing.JLabel();
        add_item_label2 = new javax.swing.JLabel();
        add_item_label3 = new javax.swing.JLabel();
        required_date_textfield = new javax.swing.JTextField();
        item_combo_box = new javax.swing.JComboBox<>();
        add_item_label = new javax.swing.JLabel();
        add_pr_button = new javax.swing.JButton();
        cancel_add_pr_button = new javax.swing.JButton();
        pr_quantity_spinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        add_sales_button.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_sales_button.setText("Add Sales");
        add_sales_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_sales_buttonActionPerformed(evt);
            }
        });

        cancel_add_sales_button.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cancel_add_sales_button.setText("Cancel");
        cancel_add_sales_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_add_sales_buttonActionPerformed(evt);
            }
        });

        quantity_spinner.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        quantity_spinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        add_item_label1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label1.setText("Key in the details of purchase requisition.");

        add_item_label2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label2.setText("Quantity:");

        add_item_label3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label3.setText("Required Date:");

        required_date_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        required_date_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                required_date_textfieldActionPerformed(evt);
            }
        });

        item_combo_box.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        add_item_label.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label.setText("Selected Item:");

        add_pr_button.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_pr_button.setText("Add PR");
        add_pr_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_pr_buttonActionPerformed(evt);
            }
        });

        cancel_add_pr_button.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cancel_add_pr_button.setText("Cancel");
        cancel_add_pr_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_add_pr_buttonActionPerformed(evt);
            }
        });

        pr_quantity_spinner.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        pr_quantity_spinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Note: Enter date in format of ddMMyyyy (01012025)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(add_item_label)
                                .addGap(120, 120, 120)
                                .addComponent(item_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(add_item_label2)
                                    .addComponent(add_item_label3))
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(required_date_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pr_quantity_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addComponent(add_item_label1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(cancel_add_pr_button, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(add_pr_button)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(add_item_label1)
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add_item_label)
                    .addComponent(item_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_item_label2)
                    .addComponent(pr_quantity_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_item_label3)
                    .addComponent(required_date_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_pr_button)
                    .addComponent(cancel_add_pr_button))
                .addGap(109, 109, 109))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_sales_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_sales_buttonActionPerformed

    }//GEN-LAST:event_add_sales_buttonActionPerformed

    private void cancel_add_sales_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_add_sales_buttonActionPerformed
        JOptionPane.showMessageDialog(this,"You have cancel adding new sales record. Back to daily sales mainpage now.");
        this.dispose();
    }//GEN-LAST:event_cancel_add_sales_buttonActionPerformed

    private void add_pr_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_pr_buttonActionPerformed
        PurchaseRequisition pr = new PurchaseRequisition();
        
        Date current_date = new Date();
        SimpleDateFormat date_format = new SimpleDateFormat("ddMMyyyy");
        String formatted_date = date_format.format(current_date);
        
        String request_id = pr.setRequestID();
        String selected_item = (String) item_combo_box.getSelectedItem();
        String user_id = SessionManager.getInstance().userID;
        int quantity = (int) pr_quantity_spinner.getValue();
        String request_date = formatted_date;
        String required_date = required_date_textfield.getText();
        String status = "Pending";

        DataMapping mapping = new DataMapping();
        Map<String, String> inventory_map = mapping.NameIdMapping(inventory_file_path);
        String group_id = inventory_map.get(selected_item);
  
        String pr_details = request_id + "|" + group_id + "|" + user_id + "|" + quantity + "|" + request_date + "|" + required_date + "|" + status;
                       
        if (quantity <=0){
            JOptionPane.showMessageDialog(this, "Please enter a valid item quantity.");
        }else if (required_date.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter the item required date");
        }else if(!ValidateFormat.date(required_date)){
            JOptionPane.showMessageDialog(this, "Invalid date format. Please enter the request date as ddMMyyyy.");
        }else if(!ValidateFormat.prItems(group_id)){
            JOptionPane.showMessageDialog(this, "The PR of this item has been raised. Please wait for it to be processed.");
        }else{
            TextFile.addLine(pr_file_path, pr_details);
            JOptionPane.showMessageDialog(this,"New PR has been raised successfully");
            this.dispose();
        }
    }//GEN-LAST:event_add_pr_buttonActionPerformed

    private void cancel_add_pr_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_add_pr_buttonActionPerformed
        JOptionPane.showMessageDialog(this,"You have cancel raising new PR. Back to PR mainpage now.");
        this.dispose();
    }//GEN-LAST:event_cancel_add_pr_buttonActionPerformed

    private void required_date_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_required_date_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_required_date_textfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SM_pr_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SM_pr_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SM_pr_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SM_pr_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SM_pr_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_item_label;
    private javax.swing.JLabel add_item_label1;
    private javax.swing.JLabel add_item_label2;
    private javax.swing.JLabel add_item_label3;
    private javax.swing.JButton add_pr_button;
    private javax.swing.JButton add_sales_button;
    private javax.swing.JButton cancel_add_pr_button;
    private javax.swing.JButton cancel_add_sales_button;
    private javax.swing.JComboBox<String> item_combo_box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner pr_quantity_spinner;
    private javax.swing.JSpinner quantity_spinner;
    private javax.swing.JTextField required_date_textfield;
    // End of variables declaration//GEN-END:variables
}
