/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.JavaY2.SalesManagerGUI;

import javax.swing.table.DefaultTableModel;
import com.mycompany.JavaY2.Class.DataMapping;
import com.mycompany.JavaY2.Class.TextFile;
import java.util.HashMap;
import java.util.Map;
/**
 *
 * @author User
 */
public class SM_po_mainpage extends javax.swing.JFrame {
    private final String po_file_path = "src/main/java/com/mycompany/JavaY2/TextFile/purchase_orders";
    private final String item_file_path = "src/main/java/com/mycompany/JavaY2/TextFile/items";
    private final String user_file_path = "src/main/java/com/mycompany/JavaY2/TextFile/users";
    private final String supplier_file_path = "src/main/java/com/mycompany/JavaY2/TextFile/suppliers"; 
    
    private final DefaultTableModel poContainer = new DefaultTableModel();
    private final String poTableColumnName[] = {"Order ID", "Request ID", "Item Name", "Raised By", "Quantity", "Unit Price", "Amount", "Supplier", "Order Date", "Order Status"};
    /**
     * Creates new form SM_po_mainpage
     */
    public SM_po_mainpage() {
        initComponents();
        populatePoTable();
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowActivated(java.awt.event.WindowEvent evt) {
                poContainer.setRowCount(0);
                populatePoTable();                                
            }
        });                
    }
    
    private void populatePoTable(){
        DataMapping mapping = new DataMapping();
        Map<String,String> item_map = mapping.IdNameMapping(item_file_path);
        Map<String,String> user_map = mapping.IdNameMapping(user_file_path);
        Map<String,String> supplier_map = mapping.IdNameMapping(supplier_file_path);
        
        Map<Integer, Map<String, String>> column_mappings = new HashMap<>();
        column_mappings.put(2, item_map);
        column_mappings.put(3, user_map);
        column_mappings.put(7, supplier_map);
        
        TextFile.populateTable(poContainer, po_table, poTableColumnName, po_file_path, 50,column_mappings);          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_item_label1 = new javax.swing.JLabel();
        homepage_button1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        po_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        add_item_label1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label1.setText("Purchase Order Table");

        homepage_button1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        homepage_button1.setText("Homepage");
        homepage_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepage_button1ActionPerformed(evt);
            }
        });

        po_table.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        po_table.setModel(poContainer);
        po_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                po_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(po_table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(homepage_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_item_label1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(add_item_label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(homepage_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(528, 528, 528))
                    .addComponent(jScrollPane1))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homepage_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepage_button1ActionPerformed
        new SM_mainpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homepage_button1ActionPerformed

    private void po_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_po_tableMouseClicked
        System.out.println(po_table.getSelectedRow());
    }//GEN-LAST:event_po_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SM_po_mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SM_po_mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SM_po_mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SM_po_mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SM_po_mainpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_item_label1;
    private javax.swing.JButton homepage_button1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable po_table;
    // End of variables declaration//GEN-END:variables
}
