/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.JavaY2.SalesManagerGUI;

import com.mycompany.JavaY2.Class.DataMapping;
import com.mycompany.JavaY2.Class.TextFile;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class SM_pr_edit extends javax.swing.JFrame {
    private final String pr_file_path = "src\\main\\java\\com\\mycompany\\JavaY2\\TextFile\\purchase_requisitions";
    private final String inventory_file_path = "src\\main\\java\\com\\mycompany\\JavaY2\\TextFile\\inventory";

    /**
     * Creates new form SM_pr_edit
     */
    public SM_pr_edit(String request_id, String item_name, String sm_id, String quantity, String request_date, String required_date, String status){
        initComponents();
        request_id_textfield.setText(request_id);
        item_name_textfield.setText(item_name);
        user_id_textfield.setText(sm_id);
        request_date_textfield.setText(request_date);
        required_date_textfield.setText(required_date);
        pr_status_textfield.setText(status);
    }
    
    private String getPrDetails(String request_id) {
        String item_name = item_name_textfield.getText();
        String sm_id = user_id_textfield.getText();
        int quantity = (int) quantity_spinner.getValue();
        String request_date = request_date_textfield.getText();
        String required_date = required_date_textfield.getText();
        String pr_status = pr_status_textfield.getText();
        
        DataMapping mapping = new DataMapping();
        Map<String,String> inventory_map = mapping.NameIdMapping(inventory_file_path);
        
        String item_group_id = inventory_map.get(item_name);
        
        String updated_pr_details = request_id + "|" + item_group_id + "|" + sm_id + "|" + quantity + "|" + request_date + "|" + required_date + "|" + pr_status;
        return updated_pr_details;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_item_label = new javax.swing.JLabel();
        item_name_label1 = new javax.swing.JLabel();
        request_id_textfield = new javax.swing.JTextField();
        request_date_textfield = new javax.swing.JTextField();
        item_name_label2 = new javax.swing.JLabel();
        item_name_label3 = new javax.swing.JLabel();
        item_name_textfield = new javax.swing.JTextField();
        item_name_label4 = new javax.swing.JLabel();
        item_name_label5 = new javax.swing.JLabel();
        item_name_label6 = new javax.swing.JLabel();
        item_name_label7 = new javax.swing.JLabel();
        user_id_textfield = new javax.swing.JTextField();
        required_date_textfield = new javax.swing.JTextField();
        pr_status_textfield = new javax.swing.JTextField();
        cancel_edit_pr_button = new javax.swing.JButton();
        edit_pr_button = new javax.swing.JButton();
        quantity_spinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 750));

        add_item_label.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label.setText("Edit the PR details.");

        item_name_label1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_label1.setText("Request ID:");

        request_id_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        request_id_textfield.setEnabled(false);

        request_date_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        request_date_textfield.setEnabled(false);

        item_name_label2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_label2.setText("Quantity:");

        item_name_label3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_label3.setText("Item Name:");

        item_name_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_textfield.setEnabled(false);

        item_name_label4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_label4.setText("Status:");

        item_name_label5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_label5.setText("Raised By:");

        item_name_label6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_label6.setText("Request Date:");

        item_name_label7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        item_name_label7.setText("Required Date:");

        user_id_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        user_id_textfield.setEnabled(false);

        required_date_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        pr_status_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        pr_status_textfield.setEnabled(false);

        cancel_edit_pr_button.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cancel_edit_pr_button.setText("Cancel");
        cancel_edit_pr_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_edit_pr_buttonActionPerformed(evt);
            }
        });

        edit_pr_button.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        edit_pr_button.setText("Edit PR");
        edit_pr_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_pr_buttonActionPerformed(evt);
            }
        });

        quantity_spinner.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        quantity_spinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item_name_label1)
                    .addComponent(item_name_label3)
                    .addComponent(item_name_label4)
                    .addComponent(item_name_label5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item_name_label2)
                    .addComponent(item_name_label6)
                    .addComponent(item_name_label7))
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(item_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(request_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(147, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(required_date_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(request_date_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pr_status_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantity_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(add_item_label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(cancel_edit_pr_button, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(edit_pr_button)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(add_item_label)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_name_label1)
                    .addComponent(request_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_name_label3)
                    .addComponent(item_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_name_label5)
                    .addComponent(user_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_name_label2)
                    .addComponent(quantity_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_name_label6)
                    .addComponent(request_date_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_name_label7)
                    .addComponent(required_date_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_name_label4)
                    .addComponent(pr_status_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_pr_button)
                    .addComponent(cancel_edit_pr_button))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_edit_pr_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_edit_pr_buttonActionPerformed
        JOptionPane.showMessageDialog(this,"You have cancel editing the PR details. Back to PR mainpage now.");
        this.dispose();
    }//GEN-LAST:event_cancel_edit_pr_buttonActionPerformed

    private void edit_pr_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_pr_buttonActionPerformed
        String request_id = request_id_textfield.getText();
        String updated_pr_details = getPrDetails(request_id);
        boolean edit_pr_success = TextFile.editTextfileRow(this, pr_file_path, request_id, 0, updated_pr_details,7 );

        if(edit_pr_success){
            JOptionPane.showMessageDialog(this,"PR has been edited successfully, back to PR mainpage now");
            this.dispose();
        }

    }//GEN-LAST:event_edit_pr_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SM_pr_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SM_pr_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SM_pr_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SM_pr_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_item_label;
    private javax.swing.JButton cancel_edit_pr_button;
    private javax.swing.JButton edit_pr_button;
    private javax.swing.JLabel item_name_label1;
    private javax.swing.JLabel item_name_label2;
    private javax.swing.JLabel item_name_label3;
    private javax.swing.JLabel item_name_label4;
    private javax.swing.JLabel item_name_label5;
    private javax.swing.JLabel item_name_label6;
    private javax.swing.JLabel item_name_label7;
    private javax.swing.JTextField item_name_textfield;
    private javax.swing.JTextField pr_status_textfield;
    private javax.swing.JSpinner quantity_spinner;
    private javax.swing.JTextField request_date_textfield;
    private javax.swing.JTextField request_id_textfield;
    private javax.swing.JTextField required_date_textfield;
    private javax.swing.JTextField user_id_textfield;
    // End of variables declaration//GEN-END:variables
}
