/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.JavaY2.SalesManagerGUI;

import com.mycompany.JavaY2.Class.TextFile;
import javax.swing.JOptionPane;
import com.mycompany.JavaY2.Class.DataMapping;
import java.util.Map;
/**
 *
 * @author User
 */
public class SM_supplier_edit extends javax.swing.JFrame {
    private final String supplier_file_path = "src\\main\\java\\com\\mycompany\\JavaY2\\TextFile\\suppliers";
    private final String item_file_path = "src\\main\\java\\com\\mycompany\\JavaY2\\TextFile\\items";
    /**
     * Creates new form SM_supplier_edit
     * @param supplier_id
     * @param supplier_name
     * @param address
     * @param contact_number
     * @param supply_item
     * @param payment_term
     */
    public SM_supplier_edit(String supplier_id, String supplier_name, String address, String contact_number, String supply_item, String payment_term) {
        initComponents();
        supplier_id_textfield.setText(supplier_id);
        supplier_name_textfield.setText(supplier_name);
        address_textfield.setText(address);
        contact_number_textfield.setText(contact_number);
        supply_item_textfield.setText(supply_item);
        payment_term_textfield.setText(payment_term);
    }

    private String getSupplierDetails(String supplier_id){
        String supplier_name = supplier_name_textfield.getText().trim();
        String address = address_textfield.getText().trim();
        String contact_number = contact_number_textfield.getText().trim();
        String supply_item_name = supply_item_textfield.getText().trim().toLowerCase();
        String payment_term = payment_term_textfield.getText().trim().toLowerCase();
        
        DataMapping mapping = new DataMapping();
        Map<String, String> item_map = mapping.NameIdMapping(item_file_path);
        
        String supply_item_id = item_map.get(supply_item_name);
                
        String supplier_details = supplier_id + "|" + supplier_name + "|" + address + "|" + contact_number + "|" + supply_item_id + "|" + payment_term;
        return supplier_details;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_item_label = new javax.swing.JLabel();
        add_item_label4 = new javax.swing.JLabel();
        add_item_label5 = new javax.swing.JLabel();
        cancel_add_supplier_button = new javax.swing.JButton();
        add_item_label1 = new javax.swing.JLabel();
        add_supplier_button = new javax.swing.JButton();
        supplier_name_textfield = new javax.swing.JTextField();
        address_textfield = new javax.swing.JTextField();
        contact_number_textfield = new javax.swing.JTextField();
        supply_item_textfield = new javax.swing.JTextField();
        payment_term_textfield = new javax.swing.JTextField();
        add_item_label2 = new javax.swing.JLabel();
        add_item_label3 = new javax.swing.JLabel();
        add_item_label6 = new javax.swing.JLabel();
        supplier_id_textfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 750));

        add_item_label.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label.setText("Edit the supplier details.");

        add_item_label4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label4.setText("Supply Item:");

        add_item_label5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label5.setText("Payment Term:");

        cancel_add_supplier_button.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cancel_add_supplier_button.setText("Cancel");
        cancel_add_supplier_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_add_supplier_buttonActionPerformed(evt);
            }
        });

        add_item_label1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label1.setText("Supplier Name:");

        add_supplier_button.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_supplier_button.setText("Edit Supplier");
        add_supplier_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_supplier_buttonActionPerformed(evt);
            }
        });

        supplier_name_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        address_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        contact_number_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        supply_item_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        payment_term_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        add_item_label2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label2.setText("Address:");

        add_item_label3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label3.setText("Contact Number:");

        add_item_label6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        add_item_label6.setText("Supplier ID:");

        supplier_id_textfield.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        supplier_id_textfield.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(cancel_add_supplier_button)
                                .addGap(169, 169, 169)
                                .addComponent(add_supplier_button))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(add_item_label6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(supplier_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(add_item_label5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(payment_term_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(add_item_label4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(supply_item_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(add_item_label3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(contact_number_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(add_item_label2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(address_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(add_item_label1)
                                    .addGap(107, 107, 107)
                                    .addComponent(supplier_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(add_item_label)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(add_item_label)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_item_label6)
                    .addComponent(supplier_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(add_item_label1))
                    .addComponent(supplier_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(address_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_item_label2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contact_number_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_item_label3))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(supply_item_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_item_label4))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(payment_term_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_item_label5))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_add_supplier_button)
                    .addComponent(add_supplier_button))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_add_supplier_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_add_supplier_buttonActionPerformed
        JOptionPane.showMessageDialog(this,"You have cancel adding new supplier. Back to supplier mainpage now.");
        this.dispose();
    }//GEN-LAST:event_cancel_add_supplier_buttonActionPerformed

    private void add_supplier_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_supplier_buttonActionPerformed

        String supplier_id = supplier_id_textfield.getText().trim();
        
        String updated_supplier_details = getSupplierDetails(supplier_id);
        boolean edit_supplier_success = TextFile.editTextfileRow(this, supplier_file_path, supplier_id, 0, updated_supplier_details, 6 );
        
        if(edit_supplier_success){
            JOptionPane.showMessageDialog(this, "Supplier has been edited successfully, back to supplier mainpage now");
            this.dispose();
        }
    }//GEN-LAST:event_add_supplier_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SM_supplier_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SM_supplier_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SM_supplier_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SM_supplier_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_item_label;
    private javax.swing.JLabel add_item_label1;
    private javax.swing.JLabel add_item_label2;
    private javax.swing.JLabel add_item_label3;
    private javax.swing.JLabel add_item_label4;
    private javax.swing.JLabel add_item_label5;
    private javax.swing.JLabel add_item_label6;
    private javax.swing.JButton add_supplier_button;
    private javax.swing.JTextField address_textfield;
    private javax.swing.JButton cancel_add_supplier_button;
    private javax.swing.JTextField contact_number_textfield;
    private javax.swing.JTextField payment_term_textfield;
    private javax.swing.JTextField supplier_id_textfield;
    private javax.swing.JTextField supplier_name_textfield;
    private javax.swing.JTextField supply_item_textfield;
    // End of variables declaration//GEN-END:variables
}
