/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.JavaY2.SalesManager;

import com.mycompany.JavaY2.Class.PurchaseRequisition;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
/**
 *
 * @author User
 */
public class AddPurchaseRequisition extends javax.swing.JFrame {

    /**
     * Creates new form AddPurchaseRequisition
     */
    public AddPurchaseRequisition() {
        initComponents();
        String file_path = "src\\main\\java\\com\\mycompany\\JavaY2\\TextFile\\inventory";

        try (BufferedReader br = new BufferedReader(new FileReader(file_path))) {
            String line;
            br.readLine(); // Skip the header line

            while ((line = br.readLine()) != null) {
                String[] columns = line.split("\\|"); // Split by '|'
                String itemName = columns[1]; // Get item_name
                jComboBox_item.addItem(itemName); // Add to JComboBox                
            }
        } catch (IOException e) {
            System.out.println("Error reading file: " + e.getMessage());
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpinner_quantity = new JSpinner(new SpinnerNumberModel(0, 0, 1000, 1));
        jComboBox_item = new javax.swing.JComboBox<>();
        jTextField_required_date = new javax.swing.JTextField();
        jButton_place_pr = new javax.swing.JButton();
        jButton_cancel_pr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Place New Purchase Requisition");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Item:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Quantity:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Required Date:");

        jSpinner_quantity.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jComboBox_item.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_itemActionPerformed(evt);
            }
        });

        jTextField_required_date.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jButton_place_pr.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton_place_pr.setText("Place PR");
        jButton_place_pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_place_prActionPerformed(evt);
            }
        });

        jButton_cancel_pr.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton_cancel_pr.setText("Cancel");
        jButton_cancel_pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancel_prActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_place_pr)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_required_date)
                                    .addComponent(jSpinner_quantity)
                                    .addComponent(jComboBox_item, 0, 203, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jButton_cancel_pr)))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_item))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_quantity))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_required_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_place_pr)
                    .addComponent(jButton_cancel_pr))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_itemActionPerformed

    }//GEN-LAST:event_jComboBox_itemActionPerformed

    private void jButton_place_prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_place_prActionPerformed

            String pr_details;
            String datePattern = "^\\d{8}$|^\\d{2}([/-])\\d{2}\\1\\d{4}$";

            
            PurchaseRequisition pr = new PurchaseRequisition();

            String item_name = jComboBox_item.getSelectedItem().toString().trim().toLowerCase();
            int quantity = (int) jSpinner_quantity.getValue();
            String required_date = jTextField_required_date.getText().trim();
            String formatted_required_date = pr.setRequiredDate(required_date);
            
            if (item_name.isEmpty() || quantity <= 0 || required_date.isEmpty()){
                JOptionPane.showMessageDialog(null, "Please enter all the fields.");
                
            }else if (!required_date.matches(datePattern)){
                JOptionPane.showMessageDialog(null, "Invalid date format. Please enter date as DD/MM/YYYY, DD-MM-YYYY, or DDMMYYYY.");
                
            }else if (formatted_required_date == null){
                JOptionPane.showMessageDialog(null, "Please key in a valid date.");
                
            }else{
                pr_details = pr.setRequestID()+ "|" + pr.setGroupID(item_name) + "|" + pr.setUserID() + "|" + quantity + "|" + pr.setRequestDate() + "|" + pr.setRequiredDate(required_date) + "|" + pr.setPRStatus();            
                pr.writePRtoFile(pr_details);
                this.dispose();
            }   
    }//GEN-LAST:event_jButton_place_prActionPerformed

    private void jButton_cancel_prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancel_prActionPerformed
        new PREntry().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_cancel_prActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPurchaseRequisition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPurchaseRequisition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPurchaseRequisition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPurchaseRequisition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPurchaseRequisition().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancel_pr;
    private javax.swing.JButton jButton_place_pr;
    private javax.swing.JComboBox<String> jComboBox_item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner jSpinner_quantity;
    private javax.swing.JTextField jTextField_required_date;
    // End of variables declaration//GEN-END:variables
}
