/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.JavaY2.SalesManager;

import com.mycompany.JavaY2.Class.PurchaseRequisition;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author User
 */
public class EditPurchaseRequisition extends javax.swing.JFrame {

    /**
     * Creates new form EditPurchaseRequisition
     * @param request_id
     * @param item_name
     * @param required_date
     */
//    public EditPurchaseRequisition(String request_id, String item_name, String user_id, String quantity, String request_date, String required_date, String pr_status) {
//        initComponents();
//        jTextField_item.setText(item_name);
//        jTextField_required_date.setText(required_date);
//    }
    public EditPurchaseRequisition(String request_id, String item_name, String required_date) {
        initComponents();
        jTextField_item.setText(item_name);
        jTextField_required_date.setText(required_date);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSpinner_quantity = new JSpinner(new SpinnerNumberModel(0, 0, 1000, 1));
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_required_date = new javax.swing.JTextField();
        jButton_edit_pr = new javax.swing.JButton();
        jButton_cancel_pr = new javax.swing.JButton();
        jTextField_item = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Edit Purchase Requisition");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Item:");

        jSpinner_quantity.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Quantity:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Required Date:");

        jTextField_required_date.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jButton_edit_pr.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton_edit_pr.setText("Edit");
        jButton_edit_pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_edit_prActionPerformed(evt);
            }
        });

        jButton_cancel_pr.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton_cancel_pr.setText("Cancel");
        jButton_cancel_pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancel_prActionPerformed(evt);
            }
        });

        jTextField_item.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField_item.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_edit_pr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_required_date, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(jSpinner_quantity)
                                    .addComponent(jTextField_item, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jButton_cancel_pr)))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_quantity))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_required_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_edit_pr)
                    .addComponent(jButton_cancel_pr))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_edit_prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_edit_prActionPerformed

        String pr_details;
        String file_path = "src\\main\\java\\com\\mycompany\\JavaY2\\TextFile\\purchase_requisitions";
        PurchaseRequisition pr = new PurchaseRequisition();
        String datePattern = "^\\d{8}$|^\\d{2}([/-])\\d{2}\\1\\d{4}$";
        
        //String item_name = jTextField_item.getText();
        String item_name = jTextField_item.getText();
        int quantity = (int) jSpinner_quantity.getValue();
        String required_date = jTextField_required_date.getText();
        String formatted_required_date = pr.setRequiredDate(required_date);
        
        if (quantity <= 0 || required_date.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter all the fields.");
        }else if (!required_date.matches(datePattern)){
            JOptionPane.showMessageDialog(null, "Invalid date format. Please enter date as DD/MM/YYYY, DD-MM-YYYY, or DDMMYYYY.");
        }else if (formatted_required_date == null){
            JOptionPane.showMessageDialog(null, "Please key in a valid date.");
        }else{
            pr_details = pr.getRequestID()+ "|" + pr.setGroupID(item_name) + "|" + pr.getUserID() + "|" + quantity + "|" + pr.getRequestDate() + "|" + pr.setRequiredDate(required_date) + "|" + "pending";
            boolean edit_pr = PurchaseRequisition.editPR(pr.getRequestID(), pr_details, file_path);
            if (edit_pr){
                JOptionPane.showMessageDialog(this, "Purchase requisition has been edited successfully!");
                this.dispose();  // Close the edit window
            }
        }

                

    }//GEN-LAST:event_jButton_edit_prActionPerformed

    private void jButton_cancel_prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancel_prActionPerformed
        new PREntry().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_cancel_prActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPurchaseRequisition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPurchaseRequisition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPurchaseRequisition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPurchaseRequisition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancel_pr;
    private javax.swing.JButton jButton_edit_pr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner jSpinner_quantity;
    private javax.swing.JTextField jTextField_item;
    private javax.swing.JTextField jTextField_required_date;
    // End of variables declaration//GEN-END:variables
}
