/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.JavaY2.SalesManager;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ItemEntry extends javax.swing.JFrame {

    private final DefaultTableModel container = new DefaultTableModel();
    private final String columnName[] = {"Item ID", "Item Name", "Stock Price", "Sales per day", "Ordering Lead Time (Days)", "Safety Level", "Supplier", "Group ID"};
    
    
    public ItemEntry() {
        initComponents();
        container.setRowCount(0);
        container.setColumnIdentifiers(columnName);
        jTable_item.setRowHeight(50);
        
        String item_file_path = "src/main/java/com/mycompany/JavaY2/TextFile/items";
        try (BufferedReader br = new BufferedReader(new FileReader(item_file_path))) {
            String line;
            Set<String> uniqueRows = new HashSet<>();
            
            br.readLine(); 
            while ((line = br.readLine()) != null) {
                if (!uniqueRows.contains(line)){
                    uniqueRows.add(line);
                    String item_details[] = line.split("\\|");
                    container.addRow(item_details);                   
                }

            }
        } catch (IOException e) {
        }
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowActivated(java.awt.event.WindowEvent evt) {
                container.setRowCount(0);
                try (BufferedReader br = new BufferedReader(new FileReader(item_file_path))) {
                    String line;
                    Set<String> uniqueRows = new HashSet<>();

                    br.readLine(); 
                    while ((line = br.readLine()) != null) {
                        if (!uniqueRows.contains(line)){
                            uniqueRows.add(line);
                            String item_details[] = line.split("\\|");
                            container.addRow(item_details);                   
                        }
                    }
                } catch (IOException e) {
                }                   
            }
        });        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JButton_Homepage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JButton_add_item = new javax.swing.JButton();
        JButton_delete_item = new javax.swing.JButton();
        JButton_edit_item = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_item = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JButton_Homepage.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        JButton_Homepage.setText("Homepage");
        JButton_Homepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_HomepageActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Item List");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1168, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JButton_add_item.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        JButton_add_item.setText("Add");
        JButton_add_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_add_itemActionPerformed(evt);
            }
        });

        JButton_delete_item.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        JButton_delete_item.setText("Delete");
        JButton_delete_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_delete_itemActionPerformed(evt);
            }
        });

        JButton_edit_item.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        JButton_edit_item.setText("Edit");
        JButton_edit_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_edit_itemActionPerformed(evt);
            }
        });

        jTable_item.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable_item.setModel(container);
        jTable_item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_itemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_item);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JButton_Homepage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButton_add_item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButton_delete_item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButton_edit_item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(JButton_Homepage)
                        .addGap(38, 38, 38)
                        .addComponent(JButton_add_item)
                        .addGap(53, 53, 53)
                        .addComponent(JButton_edit_item)
                        .addGap(50, 50, 50)
                        .addComponent(JButton_delete_item))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButton_HomepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_HomepageActionPerformed
        new sales_manager_homepage().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_JButton_HomepageActionPerformed

    private void JButton_add_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_add_itemActionPerformed
       new AddItem().setVisible(true);
    }//GEN-LAST:event_JButton_add_itemActionPerformed

    private void JButton_delete_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_delete_itemActionPerformed
        int selectedRow = jTable_item.getSelectedRow();
        
        if (selectedRow == -1){
            return;
        }
        
        String file_path = "src\\main\\java\\com\\mycompany\\JavaY2\\TextFile\\items";
        String item_id = jTable_item.getValueAt(selectedRow, 0).toString();
        
        List<String> updatedLines = new ArrayList<>();
        
        try (BufferedReader br = new BufferedReader(new FileReader(file_path))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (!line.startsWith(item_id + "|")) { // Keep only lines that do not match the ID
                    updatedLines.add(line);
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading the file.");
            return;
        }
        
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(file_path))){
            for (String updatedLine : updatedLines){
                bw.write(updatedLine);
                bw.newLine();
            }
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "Error reading textfile");
        }
        
        container.removeRow(selectedRow);
        JOptionPane.showMessageDialog(this, "Item has been deleted");
    }//GEN-LAST:event_JButton_delete_itemActionPerformed

    private void JButton_edit_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_edit_itemActionPerformed
        int selectedRow = jTable_item.getSelectedRow(); // Get selected row index

        if (selectedRow != -1) { 
            String item_id = jTable_item.getValueAt(selectedRow, 0).toString();
            String item_name = jTable_item.getValueAt(selectedRow, 1).toString();
            String stock_price = jTable_item.getValueAt(selectedRow, 2).toString();
            String sales_per_day = jTable_item.getValueAt(selectedRow, 3).toString();
            String ordering_lead_time = jTable_item.getValueAt(selectedRow, 4).toString();
            String safety_level = jTable_item.getValueAt(selectedRow, 5).toString();
            String supplier_id = jTable_item.getValueAt(selectedRow, 6).toString();
            String group_id = jTable_item.getValueAt(selectedRow, 7).toString();

            new EditItem(item_id, item_name, stock_price, sales_per_day, ordering_lead_time, safety_level, supplier_id, group_id).setVisible(true);
        }
    }//GEN-LAST:event_JButton_edit_itemActionPerformed

    private void jTable_itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_itemMouseClicked
        System.out.println(jTable_item.getSelectedRow());
    }//GEN-LAST:event_jTable_itemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_Homepage;
    private javax.swing.JButton JButton_add_item;
    private javax.swing.JButton JButton_delete_item;
    private javax.swing.JButton JButton_edit_item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_item;
    // End of variables declaration//GEN-END:variables
}
