/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.JavaY2.SalesManager;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class SupplierEntry extends javax.swing.JFrame {
    
    private final DefaultTableModel container = new DefaultTableModel();
    private final String columnName[] = {"Supplier ID", "Supplier Name", "Address", "Contact Number", "Supply Items", "Payment Term"};
    
    
    public SupplierEntry() {
        initComponents();
        container.setRowCount(0);
        container.setColumnIdentifiers(columnName);
        jTable_supplier.setRowHeight(50);
        jTable_supplier.getColumnModel().getColumn(0).setPreferredWidth(80); // Supplier ID
        jTable_supplier.getColumnModel().getColumn(1).setPreferredWidth(150); // Supplier Name
        jTable_supplier.getColumnModel().getColumn(2).setPreferredWidth(200); // Address
        jTable_supplier.getColumnModel().getColumn(3).setPreferredWidth(130); // Contact Number
        jTable_supplier.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTable_supplier.getColumnModel().getColumn(5).setPreferredWidth(300);
        
        String file_path = "src/main/java/com/mycompany/JavaY2/TextFile/suppliers";

        try (BufferedReader br = new BufferedReader(new FileReader(file_path))) {
            String line;
            Set<String> uniqueRows = new HashSet<>();
            
            br.readLine();
            while ((line = br.readLine()) != null) {
                if (!uniqueRows.contains(line)){
                    uniqueRows.add(line);
                    String supplierDetails[] = line.split("\\|");
                    container.addRow(supplierDetails);                   
                }

            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error reading file");
        }         
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowActivated(java.awt.event.WindowEvent evt) {
                container.setRowCount(0);
                try (BufferedReader br = new BufferedReader(new FileReader(file_path))) {
                    String line;
                    Set<String> uniqueRows = new HashSet<>();

                    br.readLine(); 
                    while ((line = br.readLine()) != null) {
                        if (!uniqueRows.contains(line)){
                            uniqueRows.add(line);
                            String supplierDetails[] = line.split("\\|");
                            container.addRow(supplierDetails);                   
                        }
                    }
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Error reading file");                    
                }                   
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JButton_Homepage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JButton_add_supplier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_supplier = new javax.swing.JTable();
        JButton_edit_supplier = new javax.swing.JButton();
        JButton_delete_supplier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JButton_Homepage.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        JButton_Homepage.setText("Homepage");
        JButton_Homepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_HomepageActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Supplier List");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1168, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JButton_add_supplier.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        JButton_add_supplier.setText("Add");
        JButton_add_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_add_supplierActionPerformed(evt);
            }
        });

        jTable_supplier.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable_supplier.setModel(container);
        jTable_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_supplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_supplier);

        JButton_edit_supplier.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        JButton_edit_supplier.setText("Edit");
        JButton_edit_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_edit_supplierActionPerformed(evt);
            }
        });

        JButton_delete_supplier.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        JButton_delete_supplier.setText("Delete");
        JButton_delete_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_delete_supplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JButton_add_supplier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButton_Homepage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButton_edit_supplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButton_delete_supplier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(JButton_Homepage)
                        .addGap(43, 43, 43)
                        .addComponent(JButton_add_supplier)
                        .addGap(43, 43, 43)
                        .addComponent(JButton_edit_supplier)
                        .addGap(41, 41, 41)
                        .addComponent(JButton_delete_supplier))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void JButton_HomepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_HomepageActionPerformed
        new sales_manager_homepage().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_JButton_HomepageActionPerformed

    private void JButton_add_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_add_supplierActionPerformed
       new AddSupplier().setVisible(true);    
    }//GEN-LAST:event_JButton_add_supplierActionPerformed

    private void JButton_edit_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_edit_supplierActionPerformed
        int selectedRow = jTable_supplier.getSelectedRow(); // Get selected row index

        if (selectedRow != -1) { 
            String supplier_id = jTable_supplier.getValueAt(selectedRow, 0).toString();
            String supplier_name = jTable_supplier.getValueAt(selectedRow, 1).toString();
            String address = jTable_supplier.getValueAt(selectedRow, 2).toString();
            String contact_number = jTable_supplier.getValueAt(selectedRow, 3).toString();
            String supply_item = jTable_supplier.getValueAt(selectedRow, 4).toString();
            String payment_term = jTable_supplier.getValueAt(selectedRow, 5).toString();

            new EditSupplier(supplier_id, supplier_name, address, contact_number, supply_item, payment_term).setVisible(true);
        }
    }//GEN-LAST:event_JButton_edit_supplierActionPerformed

    private void JButton_delete_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_delete_supplierActionPerformed
        int selectedRow = jTable_supplier.getSelectedRow();
        
        if (selectedRow == -1){
            return;
        }
        
        String file_path = "src\\main\\java\\com\\mycompany\\JavaY2\\TextFile\\suppliers";
        String supplier_id = jTable_supplier.getValueAt(selectedRow, 0).toString();
        
        List<String> updatedLines = new ArrayList<>();
        
        try (BufferedReader br = new BufferedReader(new FileReader(file_path))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (!line.startsWith(supplier_id + "|")) { // Keep only lines that do not match the ID
                    updatedLines.add(line);
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading the file.");
            return;
        }
        
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(file_path))){
            for (String updatedLine : updatedLines){
                bw.write(updatedLine);
                bw.newLine();
            }
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "Error reading textfile");
        }
        
        container.removeRow(selectedRow);
        JOptionPane.showMessageDialog(this, "Supplier has been deleted");
    }//GEN-LAST:event_JButton_delete_supplierActionPerformed

    private void jTable_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_supplierMouseClicked
        System.out.println(jTable_supplier.getSelectedRow());
    }//GEN-LAST:event_jTable_supplierMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_Homepage;
    private javax.swing.JButton JButton_add_supplier;
    private javax.swing.JButton JButton_delete_supplier;
    private javax.swing.JButton JButton_edit_supplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_supplier;
    // End of variables declaration//GEN-END:variables
}
