/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.JavaY2.FinanceManagerGUI;

import com.mycompany.JavaY2.Class.PDFPrinter;
import com.mycompany.JavaY2.Class.Search;
import net.sf.jasperreports.engine.JRException;

import javax.swing.table.DefaultTableModel;
import java.io.IOException;

/**
 *
 * @author User
 */
public class fm_view_PO extends javax.swing.JFrame {
   String order_ID;
   String item_ID;
   String supplier_ID;
   

    /**
     * Creates new form fm_view_PO
     * @param orderID
     */
    public fm_view_PO(String orderID) {
        this.order_ID = orderID;
        this.item_ID = Search.getFromPO(order_ID, 2);
        this.supplier_ID = Search.getFromPO(order_ID, 7);
        initComponents();
        
        order_idField.setText(this.order_ID);
        order_dateField.setText(Search.getFromPO(this.order_ID, 8));
        request_byField.setText(Search.getUsername(Search.getFromPO(this.order_ID, 3)));
        request_idField.setText(Search.getFromPO(order_ID, 1));
        supplierField.setText(Search.getSupplierName(this.supplier_ID));
        shipping_termField.setText(Search.getFromItems(this.item_ID, 4)+ " Days");
        payment_termField.setText(Search.getFromSuppliers(this.supplier_ID, 5));
        
        supplier_idLabel.setText(this.supplier_ID);
        supplier_nameLabel.setText(Search.getSupplierName(this.supplier_ID));
        supplier_addressLabel.setText(Search.getFromSuppliers(this.supplier_ID, 2));
        supplier_contactLabel.setText(Search.getFromSuppliers(this.supplier_ID, 3));
        
        total_amountField.setText(Search.getFromPO(this.order_ID, 6));
        po_statusLabel.setText(Search.getFromPO(this.order_ID, 9));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        order_dateField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        order_idField = new javax.swing.JTextField();
        request_byField = new javax.swing.JTextField();
        supplierField = new javax.swing.JTextField();
        request_idField = new javax.swing.JTextField();
        shipping_termField = new javax.swing.JTextField();
        payment_termField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        supplier_idLabel = new javax.swing.JLabel();
        supplier_nameLabel = new javax.swing.JLabel();
        supplier_addressLabel = new javax.swing.JLabel();
        supplier_contactLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        po_table = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        total_amountField = new javax.swing.JTextField();
        po_statusLabel = new javax.swing.JLabel();
        btnExport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        btnBack.setText("<");
        btnBack.setPreferredSize(new java.awt.Dimension(100, 74));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Purchase Order");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Order ID:");

        order_dateField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        order_dateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_dateFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Order Date:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Requested By:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Supplier");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Based on Purchase Requisition:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Shipping Term:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Payment Term:");

        order_idField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        request_byField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        supplierField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        supplierField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierFieldActionPerformed(evt);
            }
        });

        request_idField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        shipping_termField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        shipping_termField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shipping_termFieldActionPerformed(evt);
            }
        });

        payment_termField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Vendor");

        supplier_idLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        supplier_nameLabel.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N

        supplier_addressLabel.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N

        supplier_contactLabel.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N

        po_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {this.item_ID, Search.getItemNamebyItemID(this.item_ID), Search.getFromPO(this.order_ID, 4), Search.getFromPO(this.order_ID, 5),Search.getFromPO(this.order_ID, 6)}
            },
            new String [] {
                "Item ID", "Item Name", "Quantity", "Unit Price", "Amount"
            }
        ));
        jScrollPane1.setViewportView(po_table);

        jLabel14.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel14.setText("Total");

        total_amountField.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        po_statusLabel.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N

        btnExport.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btnExport.setText("Export As PDF");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnExportActionPerformed(evt);
                } catch (JRException e) {
                    throw new RuntimeException(e);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(671, 671, 671)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(supplier_nameLabel)
                                            .addComponent(supplier_idLabel)
                                            .addComponent(supplier_addressLabel)
                                            .addComponent(supplier_contactLabel))
                                        .addGap(632, 632, 632))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(459, 459, 459)
                                        .addComponent(btnExport))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 1254, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(po_statusLabel)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(18, 18, 18)
                                                .addComponent(total_amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, 0))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(order_idField)
                            .addComponent(order_dateField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(request_byField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supplierField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(841, 841, 841)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(payment_termField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(839, 839, 839)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(shipping_termField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(714, 714, 714)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(request_idField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnExport))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(order_idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(request_idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shipping_termField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(order_dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(payment_termField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(request_byField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(3, 3, 3)
                .addComponent(jLabel9)
                .addGap(25, 25, 25)
                .addComponent(supplier_idLabel)
                .addGap(18, 18, 18)
                .addComponent(supplier_nameLabel)
                .addGap(18, 18, 18)
                .addComponent(supplier_addressLabel)
                .addGap(18, 18, 18)
                .addComponent(supplier_contactLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(total_amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(po_statusLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new fm_purchase_order().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void order_dateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_dateFieldActionPerformed
        
    }//GEN-LAST:event_order_dateFieldActionPerformed

    private void supplierFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierFieldActionPerformed
        
    }//GEN-LAST:event_supplierFieldActionPerformed

    private void shipping_termFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shipping_termFieldActionPerformed
        
    }//GEN-LAST:event_shipping_termFieldActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) throws JRException, IOException {//GEN-FIRST:event_btnExportActionPerformed
        PDFPrinter printer = new PDFPrinter();
        PDFPrinter.PDFItem items = new PDFPrinter.PDFItem(po_table.getValueAt(0,0).toString(), 
                po_table.getValueAt(0,1).toString(), po_table.getValueAt(0,2).toString(), 
                po_table.getValueAt(0,3).toString(), po_table.getValueAt(0,4).toString());
        printer.print(order_idField.getText(), order_dateField.getText(), request_byField.getText(), 
                supplierField.getText(), request_idField.getText(), shipping_termField.getText(), payment_termField.getText(), 
                supplier_idLabel.getText(), supplier_nameLabel.getText(), supplier_addressLabel.getText(), supplier_contactLabel.getText(), 
                total_amountField.getText(), po_statusLabel.getText(), items);
    }//GEN-LAST:event_btnExportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fm_view_PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fm_view_PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fm_view_PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fm_view_PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fm_view_PO("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField order_dateField;
    private javax.swing.JTextField order_idField;
    private javax.swing.JTextField payment_termField;
    private javax.swing.JLabel po_statusLabel;
    private javax.swing.JTable po_table;
    private javax.swing.JTextField request_byField;
    private javax.swing.JTextField request_idField;
    private javax.swing.JTextField shipping_termField;
    private javax.swing.JTextField supplierField;
    private javax.swing.JLabel supplier_addressLabel;
    private javax.swing.JLabel supplier_contactLabel;
    private javax.swing.JLabel supplier_idLabel;
    private javax.swing.JLabel supplier_nameLabel;
    private javax.swing.JTextField total_amountField;
    // End of variables declaration//GEN-END:variables
}
